version: '3.7'

services:
    node-app:
        image: ibado/exercises-api
        ports:      
            - 8080:3000
        links:
            - mysql
        depends_on:
            - mysql
        restart: on-failure
    mysql:
        image: mysql:8.0.22
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - mysql.env
        ports:
            - 3306:3306
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./mysql-scripts:/docker-entrypoint-initdb.d
        restart: on-failure
